
package services.html2xml.definitions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculatorSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorSoap {


    /**
     * Add two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Add", action = "http://tempuri.org/Add")
    @WebResult(name = "AddResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Add", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.AddResponse")
    public int add(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        int a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        int b);

    /**
     * Substract two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Subtract", action = "http://tempuri.org/Subtract")
    @WebResult(name = "SubtractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Subtract", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.Subtract")
    @ResponseWrapper(localName = "SubtractResponse", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.SubtractResponse")
    public int subtract(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        int a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        int b);

    /**
     * Multiply two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Multiply", action = "http://tempuri.org/Multiply")
    @WebResult(name = "MultiplyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Multiply", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.Multiply")
    @ResponseWrapper(localName = "MultiplyResponse", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.MultiplyResponse")
    public int multiply(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        int a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        int b);

    /**
     * Divide two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Divide", action = "http://tempuri.org/Divide")
    @WebResult(name = "DivideResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Divide", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.Divide")
    @ResponseWrapper(localName = "DivideResponse", targetNamespace = "http://tempuri.org/", className = "services.calculator.definitions.DivideResponse")
    public int divide(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        int a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        int b);

}
