
package services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "NumberFault", targetNamespace = "http://localhost:11305/CalculatorService/Calculator")
public class NumberFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NumberFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NumberFault_Exception(String message, NumberFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NumberFault_Exception(String message, NumberFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: services.NumberFault
     */
    public NumberFault getFaultInfo() {
        return faultInfo;
    }

}
