
package services.html2xml.definitions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculatorHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorHttpPost {


    /**
     * Add two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Add")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int add(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "a")
        String a,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "b")
        String b);

    /**
     * Substract two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Subtract")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int subtract(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "a")
        String a,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "b")
        String b);

    /**
     * Multiply two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Multiply")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int multiply(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "a")
        String a,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "b")
        String b);

    /**
     * Divide two numbers and return the result.
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Divide")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int divide(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "a")
        String a,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "b")
        String b);

}
